name: build_tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get git tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{steps.tag.outputs.tag}}
      - name: Build and push the docker image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKER_USER }}/file_server:latest,${{ secrets.DOCKER_USER }}/file_server:${{steps.tag.outputs.tag}}
      - name: Build and push the fsrz docker image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKER_USER }}/fsrz:latest,${{ secrets.DOCKER_USER }}/fsrz:${{steps.tag.outputs.tag}}
          file: Dockerfile.fsrz
